export const SEARCH_CATEGORIES = [
  "offices",
  "corporate offices",
  "business centers",
  "commercial buildings",
  "schools",
  "clinics",
  "gyms",
  "retail stores",
  "salons",
  "factories",
  "warehouses",
  "banks",
  "law firms",
  "accounting firms",
  "insurance agencies",
  "real estate agencies",
  "medical offices",
  "dental clinics",
  "car dealerships",
  "hardware stores",
  "furniture stores",
  "electronics stores",
  "clothing stores",
  "pet stores",
  "beauty spas",
  "training centers",
  "coworking spaces",
];

export const EXCLUDED_BUSINESS_KEYWORDS = [
  "restaurant",
  "cafe",
  "café",
  "food",
  "grocery",
  "grocer",
  "supermarket",
  "bakery",
  "deli",
  "meat shop",
  "fish market",
  "catering",
  "kitchen",
  "bar",
  "pub",
  "bistro",
  "pizzeria",
  "pizza",
  "burger",
  "coffee",
  "tea house",
  "juice",
  "snack",
  "meal",
  "convenience store",
];

export const EXCLUDED_PLACE_TYPES = [
  "restaurant",
  "food",
  "cafe",
  "bakery",
  "bar",
  "meal_delivery",
  "meal_takeaway",
  "grocery_or_supermarket",
  "supermarket",
  "liquor_store",
  "convenience_store",
];

export const SUBJECT_LINE_SUGGESTIONS = [
  "Special Lunch Catering Offer Near Your Office",
  "Fresh Indian Food Deals for Your Team This Week",
  "Office Lunch Made Easy Near You",
  "Catering Special for Local Businesses",
  "Treat Your Team to Fresh Indian Food",
];

export const TEMPLATE_VARIABLES = [
  "{{business_name}}",
  "{{restaurant_name}}",
  "{{offer}}",
  "{{address}}",
  "{{phone}}",
  "{{order_link}}",
];

export const PUBLIC_PATHS = ["/", "/contact", "/about", "/catering"];
